[2024-05-23T10:51:50.474+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: UpdateSymbol_ROW.load scheduled__2024-05-22T10:00:00+00:00 [queued]>
[2024-05-23T10:51:50.479+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: UpdateSymbol_ROW.load scheduled__2024-05-22T10:00:00+00:00 [queued]>
[2024-05-23T10:51:50.480+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-05-23T10:51:50.486+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2024-05-22 10:00:00+00:00
[2024-05-23T10:51:50.489+0000] {standard_task_runner.py:57} INFO - Started process 4786 to run task
[2024-05-23T10:51:50.491+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'UpdateSymbol_ROW', 'load', 'scheduled__2024-05-22T10:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/UpdateSymbol_ROW.py', '--cfg-path', '/tmp/tmpx9yao76j']
[2024-05-23T10:51:50.493+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask load
[2024-05-23T10:51:50.520+0000] {task_command.py:416} INFO - Running <TaskInstance: UpdateSymbol_ROW.load scheduled__2024-05-22T10:00:00+00:00 [running]> on host af1541c0a54b
[2024-05-23T10:51:50.560+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='UpdateSymbol_ROW' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-22T10:00:00+00:00'
[2024-05-23T10:51:50.564+0000] {base.py:73} INFO - Using connection ID 'redshift_dev_db' for task execution.
[2024-05-23T10:52:06.892+0000] {logging_mixin.py:154} INFO - SSL SYSCALL error: EOF detected
[2024-05-23T10:52:06.892+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/UpdateSymbol_ROW.py", line 49, in load
    cur.execute(f"CREATE TEMP TABLE t AS SELECT * FROM {schema}.{table};")
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/UpdateSymbol_ROW.py", line 69, in load
    cur.execute("ROLLBACK;")
psycopg2.InterfaceError: cursor already closed
[2024-05-23T10:52:06.898+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=UpdateSymbol_ROW, task_id=load, execution_date=20240522T100000, start_date=20240523T105150, end_date=20240523T105206
[2024-05-23T10:52:06.905+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task load (cursor already closed; 4786)
[2024-05-23T10:52:06.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-23T10:52:06.920+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
